### ISSUE TITLE
Array indices in cube_registration

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/NIRC2_Preprocessing#15]
Hi @henry-ngo 

I've spotted a couple of issues in NIRC2_Preprocessing, in the function cube_registration(). 

First, the call to "frame_center" at line 1887 return the (y,x) coordinates, while the call to "cube_crop_frames" at line 1903 requires the third argument to be ordered as (x,y). The call at line 1903 should thus be modified.

Second, these (x,y) inputs should be integers. In principle, floats can be accepted as indices for numpy arrays, but it looks like this is not always the case (it crashes on my freshly installed conda environment for some reason).

Proposed fix for line 1903 -- although there is certainly a more elegant way to do:
reg_crop = cube_crop_frames(reg, cube_output_size, (int(center_cube[1]),int(center_cube[0])), verbose=False)

By the way, I'm also wondering whether there is not an inconsistency between various NIRC2_Preprocessing functions regarding the (x,y) and (y,x) ordering. It seems to me that vortex_center_routine is expecting (x,y), while vortex_center is expecting (y,x). So far it hasn't lead to any problem since our images are square, but it might be a good idea to check that anyway.

Cheers,
Olivier

**Comment by henry-ngo** [comment]
Thanks @oabsil 

I will make the proposed fix for line 1903. That's too bad that "frame_center" and "cube_crop_frames" ask for different coordinate ordering, but these functions are in the VIP package. 

I will also open a new issue to ensure consistency of coordinate ordering for all NIRC2_Preprocessing functions. My plan is to make them all (y,x) since that's the standard python ordering for 2-d arrays.

**Comment by ehuby** [comment]
Hi @henry-ngo and @oabsil 

Lately, I've been investigating the cube_registration and vortex_center_from_dust_signature functions quite in detail. I'd like to share here some comments and suggestions that I have.

First, concerning mixing (x,y) and (y,x), I think there's no issue on that matter (otherwise the centering would have been wrong). When looking at the code in details, it can be confusing because x and y are sometimes inverted to comply with the right order, but the result seems correct.

Second, I would like to submit one important modification proposal. There is currently an issue if the rough estimates of the dust/vortex center coordinates are decimals (i.e. not rounded to integer values). For instance, if you specify vortex_center = (519.5, 730.) within the vortex_options structure, the returned x coordinates will be offset by 0.5 pixel.
I propose to fix this by adding these lines after line 1172:
cx = int(np.round(cx))
cy = int(np.round(cy))

Finally, I noticed that the coordinates that are returned by vortex_center_from_dust_signature are, by default, given in the reference frame of the DS9 display (starting at pixel 1 instead of 0 in python), i.e. there's a shift of 1 pixel with respect to the actual coordinates that are used in python. There's actually a keyword, ds9_indexing appearing in the sub-functions, which is set to True by default, thus inducing the 1 pixel shift, but it could be set to False to avoid it. However, this keyword is not available as input of vortex_center_from_dust_signature.
I would actually suggest that we remove this option completely and make all coordinates start from 0, to avoid any confusion.

Cheers,
Elsa.
