### ISSUE TITLE
'listing' function needs a tweak

### ISSUE THREAD

**Issue by mb2448** [vortex-exoplanet/NIRC2_Preprocessing#3]
when using listing to list files in a directory, the function requires a '/' at the end of the directory or it gives unwanted behavior 

if I do listing('/Users/Me/fitsdata')
['/Users/Me/fitsdatan0372.fits'](incorrect, note compression of directory and file)

If I do listing('/Users/Me/fitsdata/')
['/Users/Me/fitsdata/n0372.fits']

A solution would be something like this:

def listing(dirpath, filetype='pdf'):
    files=[] 
    for dirpath,_,filenames in os.walk(rootdir):
        for f in filenames:
            if f.endswith(filetype):
                files.append(os.path.abspath(os.path.join(dirpath, f)))
    return files

**Comment by ghost** [comment]
Dear mysterious Github user,

Thanks for spotting this unwanted behavior. I've just updated the code to take into account this. 

Thanks for your suggestion but instead of using a two for-loop, I prefer continue using list comprehension. So I've added a test to check if there is a missing '/' or not, then let the remaining code unchanged. This can be summarized by:

def listing(dirpath, filetype='pdf'):
if not dirpath.endswith('/'): dirpath += '/'
files = [f for f in listdir(dirpath) if isfile(join(dirpath,f)) if f.endswith(filetype)]
return files

Cheers,
Olivier
