### ISSUE TITLE
NIRC2_Preprocessing.cube_registration() returns empty array

### ISSUE THREAD

**Issue by henry-ngo** [vortex-exoplanet/NIRC2_Preprocessing#4]
This issue was found by trying to resolve another issue in VIP (see https://github.com/vortex-exoplanet/VIP/issues/24).

When trying to run NIRC2_Preprocessing.cube_registration() on one of our targets, I got an empty array as the return value. I then checked the initial guesses for the vortex center and the dust center and found that the values I was using was a few pixels different:

Original values: 
dust_center = (599,605)
dust_box_size = 41
vortex_center = (528,730)
vortex_box_size = 28

New values:
dust_center = (598,605)
dust_box_size = 41
vortex_center = (525,729)
vortex_box_size = 28

This was weird because the other two targets imaged that night used the "original values" guesses and there were no problems. The target with the issue was immediately after the first two targets (with no issues) so I don't think the vortex would have moved that much? 

I think it would help if:
1. cube_registration() throws an exception (or outputs some kind of error message) if the output is empty.
2. We think of some other way of getting an initial guess for dust/vortex position without having to supply it?

Please let me know if you need more details! I can provide the FITS files if you think that would help.

**Comment by ghost** [comment]
Hi Henry,

It's quite difficult to me to figure out what went wrong because I cannot reproduce the issue, that is to say having an empty array returned by **cube_registration()**. The differences between "Original" and "New" values shouldn't affect the **cube_registration()** behavior in a manner which might return an empty array. Indeed, the "Original" or "New" values are used with **vortex_center_from_dust_signature()** to create the _center_all_ array which would raise an exception in **cube_registration()** if it was empty. Then, _center_all_ is passed to **cube_registration()** together with a cube (for instance sci_preprocessed). When calling **cube_registration()**, if _cube_output_size_ is not _None_ and if the cube is empty but with a valid shape, for instance (0,1024,1024), then no error is raised and the resulting registered/cropped cube is empty. Could you please check the size of the cube passed to **cube_registration()** as well as the size of the cube at the two different stages of the **cube_registration()** running (_reg_ and _reg_crop_) ? The latter can be done by pulling the latest version of NIRC2_Preprocessing and then inserting respectively:
1/

``` Python
print cube.shape
```

before

``` Python
    for i,frame in enumerate(cube):
        shift =  center_cube - (center_all[i,:]-based) 
        reg[i,:,:] = frame_shift(cube[i,:,:],shift[1],shift[0])
```

2/

``` Python
print reg.shape
```

before

``` Python
    reg_crop = cube_crop_frames(reg, cube_output_size, center_cube[0], 
                                center_cube[1], verbose=False)
```

Furthermore, did you set _cube_output_size_ to None ? If yes, would you check its value by inserting

``` Python
   print 'cube_output_size = {}'.format(cube_output_size)
```

after

``` Python
if cube_output_size%2==0: cube_output_size -= 1
```

Thanks in advance.
Olivier

**Comment by henry-ngo** [comment]
Silly question: 

I'm using sourcetree to pull updates from git. I find the NIRC2_Preprocessing.py file on my machine and edit it with the 3 changes you suggested above. I think I have the right file because it's the same path as I told sourcetree. (I also right click on the filename in sourcetree and choose "open containing folder" so that I can edit the right file).

But, when trying to run the code, nothing gets printed. I even added a new line that just prints a greeting when cube_registration is called. But no output is shown.

I'm really new to using git or any kind of repository/version control. Is there a simple step I'm missing when trying to edit my local version?

Henry

**Comment by henry-ngo** [comment]
Okay, I figured out the above problem. It was a silly newbie mistake where I had the wrong NIRC2_Preprocessing.py file being read. I can now provide the output to the three print statements you requested. To answer your other question, yes, I did set "cube_output_size" to None.

There are two calls to cube_registration, one for the science frames and one for the sky frames, both of which give empty array outputs

Science frames:
cube.shape = (30, 1024, 1024)
cube_output_size = -1.0
reg.shape = (30, 1024, 1024)
OUTPUT = array([], shape=(30, 0, 0), dtype=float64)

Sky frames:
cube.shape = (1, 1024, 1024)
cube_output_size = -1.0
reg.shape = (1, 1024, 1024)
OUTPUT = array([], shape=(1, 0, 0), dtype=float64)

**Comment by ghost** [comment]
Hi Henry,

Thanks for the update. Now it becomes clear: the _cube_output_size_ applied to the _reg_crop_ is -1, which leads to an empty cube in both cases. Indeed, reg.shape = (30,1024,1024) while reg_crop.shape = (0,1024,1024) because it automatically extract an array of size 0 from the reg array. 
First, I suggest that you try to run **cube_registration()** with _cube_output_size_ set to whatever except _None_, let say 101. It should return an array with shape (30, 101, 101). 
Secondly, we have to figure out why the function **optimized_frame_size()** (called inside **cube_registration()** when _cube_output_size_ is set to None) returns -1. Let me note that when **vip.calib.fram_shift()** performs the registration, it fills the boundaries with zeros. Like the so-called _longest common substring problem", the *_optimized_frame_size()*\* function determines the size (from the center) of the largest common part of the cube frames without any zero values. Now, the _center_all_ values might play a significant role. If _center_all_ contains two very different positions (for instance because of the presence of a bad frame in the cube), the two corresponding frames will be shifted in such a way they won't share any non-zero common part. This can explain why _cube_output_size_ is < 1.
I suggest that you send to me the set of data together with any relevant information, so I can take a look.

Olivier

**Comment by oabsil** [comment]
Dear Henry,

I'm generally using the following trick to make sure that I'm using the 
proper version of NIRC2_Preprocessing.py. You may find it useful:

---

# Add NIRC2_Preprocessing in your system path if needed

import sys
sys.path.insert(0, '/Users/oabsil/Python/NIRC2_Preprocessing/')

# Import all relevant packages

from NIRC2_Preprocessing import *

---

This also allows you to put your notebook in any directory you like (not 
necessarily in the NIRC2_Preprocessing folder).

Cheers,
Olivier.

Le 16/12/15 00:40, Henry Ngo a écrit :

> Okay, I figured out the above problem. It was a silly newbie mistake 
> where I had the wrong NIRC2_Preprocessing.py file being read. I can 
> now provide the output to the three print statements you requested. To 
> answer your other question, yes, I did set "cube_output_size" to None.
> 
> There are two calls to cube_registration, one for the science frames 
> and one for the sky frames, both of which give empty array outputs
> 
> Science frames:
> cube.shape = (30, 1024, 1024)
> cube_output_size = -1.0
> reg.shape = (30, 1024, 1024)
> OUTPUT = array([], shape=(30, 0, 0), dtype=float64)
> 
> Sky frames:
> cube.shape = (1, 1024, 1024)
> cube_output_size = -1.0
> reg.shape = (1, 1024, 1024)
> OUTPUT = array([], shape=(1, 0, 0), dtype=float64)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/vortex-exoplanet/NIRC2_Preprocessing/issues/4#issuecomment-164932563.

## 

---

Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46

## Email: absil (at) astro.ulg.ac.be

**Comment by henry-ngo** [comment]
When I set cube_output_size to 101, it returns:

cube.shape = (30, 1024, 1024)
cube_output_size = 101
reg.shape = (30, 1024, 1024)
OUTPUT is indeed (30, 101, 101)

So that is working the way you expect!

For the second topic. I checked the center_all values and they are all similar to each other. However, the values are strange (I think?): 

center_all = array([[ 2181.6240445 ,   919.82399295],
       [ 2181.63480061,   919.81325634],
       [ 2181.63762021,   919.81857872],
       [ 2181.63416113,   919.80992492],
       [ 2181.63702855,   919.81631534],
       [ 2181.64142206,   919.82334585],
       [ 2181.63725279,   919.81952506],
       [ 2181.64281729,   919.82815182],
       [ 2181.64451212,   919.82023084],
       [ 2181.63367224,   919.81330835],
       [ 2181.6327615 ,   919.82679425],
       [ 2181.64405812,   919.81078841],
       [ 2181.6358613 ,   919.82011255],
       [ 2181.63930846,   919.82297593],
       [ 2181.63639295,   919.81922064],
       [ 2181.64011776,   919.82829725],
       [ 2181.63855512,   919.83821836],
       [ 2181.63874394,   919.81640672],
       [ 2181.62839377,   919.82455639],
       [ 2181.64052883,   919.81567854],
       [ 2181.63832807,   919.82159014],
       [ 2181.62242803,   919.82158647],
       [ 2181.63041605,   919.82500033],
       [ 2181.61441745,   919.8248811 ],
       [ 2181.63206551,   919.82392233],
       [ 2181.62072747,   919.82835194],
       [ 2181.61611775,   919.82030801],
       [ 2181.61732387,   919.82867916],
       [ 2178.31422185,   917.89184954],
       [ 2181.62415333,   919.83570514]])

I think this is causing the problem, because in **cube_registration()**, these _center_all_ values causes the _shift_ values computed to shift everything off the chip, so that you are left with a cube of all zeros. This cube of all zeros gets passed to **optimized_frame_size()** and after putting a few print statements to follow the logic, it outputs _size_min_ = -1. I also confirmed that it is indeed a cube of all zeros being passed to **optimized_frame_size()**

I've attached a file with the code segment I've been running as well as the necessary data files. In the code, you'll have to change the path to the files to where-ever you choose to put them on your machine.

I can't attach it in this bug report, so it is now hosted on Caltech's temporary Dropbox (link only valid for 24 hours, let me know if you need me to make it again): https://dropbox.caltech.edu/cgi-bin/dropbox.cgi?get=1&key=f97a8afbd0794c1e17c6395d6e4a69ba (100MB)

**Comment by henry-ngo** [comment]
I thought I would also start trying to figure out why the center_all values are weird. So, I looked into **vortex_center_from_dust_signature()**. I printed some of the values:

center_all_dust = [[ 602.30982265  606.93214341] ...]  # just for one frame, but similar for all frames
center_vortex_in_sky = [[ 2181.62796288   919.82580473]]
center_dust_in_sky = [[ 602.31374104  606.93395519]]
relative position = [ 1579.31422185   312.89184954]

This makes me think the value _center_vortex_in_sky_ is the problem. So, then for the call to **vortex_center_routine()** that computes center_vortex_in_sky, I turned verbose=True and get this message:

FIND SIGNATURE CENTER

At least one numerical minimization has not converged.

So, this suggests to me that perhaps this is where the problem is? At this point, I am not sure I can dig any further. Hopefully the data files linked can help point to the reason why the minimization didn't converge?

**Comment by ghost** [comment]
Hi Henry,

Thanks for your messages and sorry for my late reply.

I've tried to figure out from where the problem comes from. I think I might have found an answer. 
First, when I ran your code segment (attached to your zip file) together with your data and I confirm that it reproduced the weird behavior we discussed above. 
After having examined my code, I've taken a look to your flat images and they definitely don't look like what I expected. Actually, I would say that your flat images look like sky images.
Here is the n0585.fits flat image (it's the same for the other ones):
![henri_flat_n0585](https://cloud.githubusercontent.com/assets/12697755/11991600/8b0e5cfc-aa1c-11e5-8919-ad3fc2eed810.jpeg)

and here is what I expected to see:
![nirc2_flat](https://cloud.githubusercontent.com/assets/12697755/11991649/ff58dc0e-aa1c-11e5-8aa8-a5552e282251.png)

Therefore, I tried to run your code segment by just replacing your flat images with the ones I have (that is to say without changing a word in my NIRC2 source code) and ... everything worked. The cube "cube_reg_0227" is no more empty, the preprocessed images look fine to me, and the center_sci = array([[ 527.32090697,  730.78547527],
       [ 527.32134044,  730.7837505 ],
       [ 527.3289279 ,  730.78230291],
       [ 527.33533676,  730.78292803],
       [ 527.3255981 ,  730.7826117 ],
       [ 527.33372659,  730.78733263],
       [ 527.32475803,  730.78556248],
       [ 527.33237947,  730.79174694],
       [ 527.33025584,  730.78428085],
       [ 527.3236677 ,  730.7817358 ],
       [ 527.32322082,  730.78708691],
       [ 527.33073195,  730.78022737],
       [ 527.32669496,  730.78375726],
       [ 527.33153838,  730.78588547],
       [ 527.33225609,  730.78245651],
       [ 527.32912466,  730.78727445],
       [ 527.32912901,  730.79494511],
       [ 527.32435435,  730.781677  ],
       [ 527.31825121,  730.78432959],
       [ 527.32317941,  730.78177881],
       [ 527.32499546,  730.78772976],
       [ 527.32219672,  730.7901104 ],
       [ 527.32507806,  730.79039947],
       [ 527.3204847 ,  730.78922066],
       [ 527.3251951 ,  730.79266395],
       [ 527.32521331,  730.78887445],
       [ 527.32372417,  730.78758433],
       [ 527.32119719,  730.79126662],
       [ 527.32145957,  730.79124838],
       [ 527.32093492,  730.79267355]])

looks reliable unlike the ones you mentioned in your penultimate message. If you flat-preprocess the sci and sky images with a sky-looks-like image, it will completely bias the resulting preprocessed images. Indeed, the dust and vortex signatures are almost completely removed which can make the NIRC2 code crazy ;-)
As a conclusion, I would suggest that the problem didn't come from the NIRC2 source code but from the "flat" images.

Did you always use such kind of flat images ? 

I wish you a Merry Christmas !
Olivier

**Comment by henry-ngo** [comment]
Thanks Olivier!

I was using those flat images because the log on 26 Oct labelled them as "qacitflats" and so I thought we should be using flats with the mask in place. I am now using flats from Oct 25 that look like the regular NIRC2 flat field (and the one you showed). With the correct flats, the code now works as expected! It makes sense how the flats with the mask in place would cause problems.

Fortunately, it's an easy thing to switch out the wrong flat files with the right ones and I've re-run all of the old targets too (only a few were complete before running into this issue). Thank you!

Merry Christmas :)

**Comment by henry-ngo** [comment]
I'm able to get this to work for all data taken since the survey started now, with one exception from last week. There is no rush for this so please don't interrupt your Christmas break :)

My question is whether or not it makes sense for **cube_registration()** to return a different size cube for the science and sky images. My science cube is (19,589,589) but the sky cube is (1,591,591). I can force the size to be whatever I want by setting _cube_output_size=591_ (for example). But I am looking to automate this and I don't want to have to 1) wait for it to crash and then enter the size and 2) enter a custom size for each target. For when you get back, any thoughts?

**Comment by oabsil** [comment]
Hi Henry,

> My question is whether or not it makes sense for 
> _cube_registration()_to return a different size cube for the science 
> and sky images. My science cube is (19,589,589) but the sky cube is 
> (1,591,591). I can force the size to be whatever I want by setting 
> /cube_output_size=591/(for example). But I am looking to automate this 
> and I don't want to have to 1) wait for it to crash and then enter the 
> size and 2) enter a custom size for each target. For when you get 
> back, any thoughts? 

Olivier has designed this routine to search for the largest possible 
square field containing no zeros (masked region) around the vortex 
center. Why the output size is not the same for the science and the sky 
is not clear to me. Is (are) the sky(s) taken close enough in time to 
the science frames?

In order to avoid this behaviour, I would suggest that you force the 
image size to a reasonable number of pixels, small enough that zeros 
will not be included in the cropped image (e.g., 581 pixels). You might 
also think about overrulling the "no zero" criterion, and define the FoV 
based on the largest inscribed circle, which would make sense when using 
an annular PCA for instance. In this way, you would get the largest 
possible field. I've not tested that yet, so I'm not sure whether it 
would work.

Cheers,
Olivier.

## 

---

Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46

## Email: absil (at) astro.ulg.ac.be
